
services:
  # nginx
  web:
    build:
      context: "./nginx/"
      dockerfile: Dockerfile
    volumes:
      - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
    
  # php
  app:
    build:
      context: "./php/"
      dockerfile: Dockerfile
      target: "${BUILD_TARGET:-app}"
    volumes:
      - "./app:/var/www/html"
      - "./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro"
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    
  # mysql
  db:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  mysqldata:
